/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "on-tertiary": "#FFFFFF",
              "secondary-fixed-dim": "#34C759",
              "tertiary-fixed": "#A78BFA",
              "on-primary-container": "#FFFFFF",
              "on-primary-fixed": "#0F172A",
              "on-tertiary-container": "#FFFFFF",
              "text-secondary": "#475569",
              "on-secondary-fixed": "#0F172A",
              "on-background": "#0F172A",
              "surface-container-low": "#F8FAFC",
              "tertiary-fixed-dim": "#A78BFA",
              "text-primary": "#0F172A",
              "secondary": "#34C759",
              "primary-fixed": "#4DA8FF",
              "surface-container": "#FFFFFF",
              "glass-border": "rgba(0, 0, 0, 0.1)",
              "surface-charcoal": "#FFFFFF",
              "background": "#F8FAFC",
              "surface": "#F8FAFC",
              "on-error": "#FFFFFF",
              "on-secondary-container": "#FFFFFF",
              "outline": "#CBD5E1",
              "inverse-primary": "#4DA8FF",
              "on-secondary-fixed-variant": "#0F172A",
              "surface-variant": "#F1F5F9",
              "surface-container-lowest": "#F8FAFC",
              "surface-container-high": "#FFFFFF",
              "error-container": "#FEE2E2",
              "on-surface": "#0F172A",
              "secondary-container": "#34C759",
              "secondary-fixed": "#34C759",
              "on-tertiary-fixed": "#0F172A",
              "surface-dim": "#F8FAFC",
              "surface-tint": "#4DA8FF",
              "outline-variant": "#E2E8F0",
              "primary-container": "#4DA8FF",
              "primary-fixed-dim": "#4DA8FF",
              "surface-bright": "#FFFFFF",
              "tertiary-container": "#A78BFA",
              "tertiary": "#A78BFA",
              "on-surface-variant": "#475569",
              "on-tertiary-fixed-variant": "#0F172A",
              "on-secondary": "#FFFFFF",
              "surface-container-highest": "#FFFFFF",
              "error": "#EF4444",
              "primary": "#4DA8FF",
              "inverse-surface": "#0F172A",
              "on-primary-fixed-variant": "#FFFFFF",
              "on-error-container": "#7F1D1D",
              "inverse-on-surface": "#F8FAFC",
              "warning-amber": "#FBBF24",
              "on-primary": "#FFFFFF"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "section-gap": "120px",
              "stack-lg": "32px",
              "stack-sm": "8px",
              "gutter": "24px",
              "stack-md": "16px",
              "container-max": "1280px",
              "margin-mobile": "20px"
      },
      "fontFamily": {
              "headline-xl": ["Outfit"],
              "display-lg": ["Outfit"],
              "label-sm": ["Inter"],
              "headline-xl-mobile": ["Outfit"],
              "body-md": ["Inter"],
              "headline-md": ["Outfit"],
              "body-lg": ["Inter"],
              "display-lg-mobile": ["Outfit"]
      },
      "fontSize": {
              "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "display-lg": ["72px", {"lineHeight": "80px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "headline-xl-mobile": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "500"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "display-lg-mobile": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "700"}]
      }
    },
  },
}
